before_script:
  - gem install dpl
test:
  type: test
  script:
  - npm run test
dev:
  type: deploy
  script:
  - dpl --provider=heroku --app=shopmycourses-web-dev --api-key=$HEROKU_API_KEY
  only:
  - master
